version: '3.7'

services:
  db:
    container_name: sqlserver
    image: solomiosisante/sqlserver:dev2019
    environment:
      SA_PASSWORD: "P@ssw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "14344:1433"
    hostname: sqlserver
    volumes:
      - "./AccSol.EF/Data:C:\\scripts"    
    networks:
      accsolnet:
        ipv4_address: 172.20.0.12
  webapp:
    container_name: accsol
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: ./AccSol/Dockerfile
    ports:
      - "7010:7010"
    depends_on:
      - db
    hostname: AccSol
    networks:
      accsolnet:
        ipv4_address: 172.20.0.10
    expose:
        - "7010"
  api:
    container_name: accsol.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: ./AccSol.API/Dockerfile
    ports:
      - "7040:7040"
    depends_on:
      - db
    hostname: AccSol.API
    networks:
      accsolnet:
        ipv4_address: 172.20.0.11
    expose:
      - "7040"
    
networks:
  accsolnet:
    name: accsolnet
    driver: nat
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
